# Generated by Django 2.2.4 on 2019-08-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvote',
            field=models.BooleanField(default=True),
        ),
    ]
